---
title: "Harry Bernholz_A1"
author: "Harry Bernholz"
date: "9/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
setwd("~/Desktop/publpol118x/a1")
```

```{r}
library(tidyverse)

year <- 2020
quarters <- 1:4
type <- "Electric"

pge_20_elec <- NULL

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_20_elec <- rbind(pge_20_elec,temp)

  saveRDS(pge_20_elec, "pge_20_elec.rds")
}

```

```{r}
library(tidyverse)

year <- 2017
quarters <- 1:4
type <- "Electric"

pge_17_elec <- NULL

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_17_elec <- rbind(pge_17_elec,temp)

  saveRDS(pge_17_elec, "pge_17_elec.rds")
}
```

```{r}
library(tidyverse)

year <- 2018
quarters <- 1:4
type <- "Electric"

pge_18_elec <- NULL

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_18_elec <- rbind(pge_18_elec,temp)

  saveRDS(pge_18_elec, "pge_18_elec.rds")
}
```

```{r}
library(tidyverse)

year <- 2019
quarters <- 1:4
type <- "Electric"

pge_19_elec <- NULL

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_19_elec <- rbind(pge_19_elec,temp)

  saveRDS(pge_19_elec, "pge_19_elec.rds")
}
```

```{r}
library(tidyverse)

year <- 2021
quarters <- 1:2
type <- "Electric"

pge_21_elec <- NULL

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_21_elec <- rbind(pge_21_elec,temp)

  saveRDS(pge_21_elec, "pge_21_elec.rds")
}
```

```{r}
pge_elec_17_21 <- rbind(pge_17_elec, pge_18_elec, pge_19_elec, pge_20_elec, pge_21_elec)
```

```{r}
pge_filter <- 
  filter(
    pge_elec_17_21,
    CUSTOMERCLASS %in% 
      c(
        "Elec- Residential",
        "Elec- Commercial"
      )
  )
```

```{r}
table(pge_filter$COMBINED)
```

```{r}
pge_select <-
  select(
    pge_filter,
    -c(COMBINED, AVERAGEKWH)
  )
```

```{r}
pge_group <-
  group_by(
    pge_select,
    MONTH,
    CUSTOMERCLASS
  )
```

```{r}
pge_summarize <-
  summarize(
    pge_group,
    TOTALKWH = 
      sum(
        TOTALKWH, 
        na.rm = T
      ),
    TOTALCUSTOMERS =
      sum(
        TOTALCUSTOMERS,
        na.rm = T
      ),
    TOTALKBTU =
      TOTALKWH*3.412
  )

pge_mutate <-
  mutate(
    pge_summarize,
    AVERAGEKBTU =
      TOTALKBTU/TOTALCUSTOMERS
  )
```

```{r}
pge_mutate_res <-
  filter(
    pge_mutate,
    CUSTOMERCLASS %in% 
      c(
        "Elec- Residential"
  )
  )
```

```{r}
pge_mutate_com <-
  filter(
    pge_mutate,
    CUSTOMERCLASS %in% 
      c(
        "Elec- Commercial"
  )
  )
```

```{r}
library(tidyverse)
library(plotly)

pge_chart_res <-
  pge_mutate_res %>% 
  ggplot() +
  geom_bar(
    aes(
      x = MONTH %>% factor(),
      y = TOTALKBTU,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Month",
    y = "kBTU",
    title = "PG&E Territory Monthly Electricity Usage (Residential)",
    fill = "Electricity Type"
  )

mutate(
    DATE = 
      paste(
        "2020",
        "03", 
        "01",
        sep="-"
      ) %>% as.Date()
  )

pge_chart_res %>% ggplotly()

```






```



